/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajaMedica;

import java.math.BigInteger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author daiyd
 */
public class PedirFicha extends javax.swing.JFrame {

    Conexion con = null;
    Statement stmt = null;
    PreparedStatement prpInser = null;
    String EMPTY = new String();

    /**
     * Creates new form PedirFicha
     */
    public PedirFicha() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cedula = new javax.swing.JLabel();
        tDocumento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TipoPaciente = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cOpciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cedula.setText("Documento");

        tDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDocumentoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("Petición de Ficha");

        TipoPaciente.setText("Tipo de Paciente");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOpcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(btnEnviar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(Cedula)
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TipoPaciente)
                                .addComponent(tDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula)
                    .addComponent(tDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(TipoPaciente)
                .addGap(18, 18, 18)
                .addComponent(cOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnLimpiar))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDocumentoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        con = new Conexion();
        boolean encontrado = false;
        if ("".equals(tDocumento.getText())) {
            JOptionPane.showMessageDialog(null, "Guardado Fallido\nAsegurese de completar todos los campos", "Guardado Fallido", JOptionPane.ERROR_MESSAGE);
        } else {
            if (Validador.numeros(tDocumento.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Dato Erroneo\nSolo digite numeros en el campo Codigo", "Dato Erroneo", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    Long iDocumento = Long.parseLong(tDocumento.getText());
                    //String sGenral = cOpciones.getSelectedItem().toString();
                    String query = "SELECT * FROM \"Usuario\" WHERE documento = ?;";
                    PreparedStatement pre = con.open().prepareStatement(query);
                    pre.setLong(1, iDocumento);
                    ResultSet datos = pre.executeQuery();
                    String iCod;

                    while (datos.next()) {
                        encontrado = true;
                        iCod = datos.getString(5);
                        tDocumento.setText(iCod);
                    }
                    pre.close();
                    con.close();
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(null, "Codigo Repetido\nAsegurese de que no se repita", "Guardado Fallido", JOptionPane.ERROR_MESSAGE);
                }
                if (encontrado == false) {
                    JOptionPane.showMessageDialog(null, "No se encontró\nel usuario", "Guardado Fallido", JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Turno pedido\ncon exito", "Guardado Correcto", JOptionPane.PLAIN_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        tDocumento.setText("");
        cOpciones.setSelectedItem(EMPTY);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOpcionesActionPerformed
        
    }//GEN-LAST:event_cOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel TipoPaciente;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tDocumento;
    // End of variables declaration//GEN-END:variables
}
